org: anguspbezzina
app: portfolio-backend
service: portfolio-backend

useDotenv: true

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs20.x
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  generatePresignedUrl:
    handler: dist/generatePresignedCVUrl.handler
    events:
      - httpApi:
          path: /download
          method: post
    environment:
      S3_ACCESS_KEY_ID: "${env:S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${env:S3_SECRET_ACCESS_KEY}"
      S3_REGION: "${env:S3_REGION}"
      S3_BUCKET_NAME: "${env:S3_BUCKET_NAME}"
  createAirtableRecord:
    handler: dist/createAirtableRecord.handler
    events:
      - httpApi:
          path: /airtable
          method: post
    environment:
      AIRTABLE_API_KEY: "${env:AIRTABLE_API_KEY}"
      AIRTABLE_BASE: "${env:AIRTABLE_BASE}"
      AIRTABLE_TABLE: "${env:AIRTABLE_TABLE}"
  chatbot:
    handler: dist/chatbot.handler
    events:
      - httpApi:
          path: /chatbot
          method: post
    environment:
      LANGCHAIN_API_KEY: "${env:LANGCHAIN_API_KEY}"
      LANGCHAIN_TRACING_V2: "${env:LANGCHAIN_TRACING_V2}"
      OPENAI_API_KEY: "${env:OPENAI_API_KEY}"

custom:
  serverless-offline:
    babelOptions:
      presets: ["env"]
